### ISSUE TITLE
Tatung Einstein 256

### ISSUE THREAD

**Issue by tmznix** [MiSTer-devel/TatungEinstein_MiSTer#1]
Are you planning on supporting the follow on machine to the TC-01, the Einstein256 ?
Its basically the same as the original, with improved video (Yamaha V9938), and a lot of more video RAM.

Source code for the v9938 is here:

https://github.com/kunichiko/ese-vdp

Great Work! I will test it this weekend :)
Cheers!

**Comment by pcornier** [comment]
Yes this is in my plans. Thanks for the link.

**Comment by pcornier** [comment]
256 is available now.
